# This workflow builds the project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code base
        # https://github.com/actions/checkout
        uses: actions/checkout@v2.3.1

      - name: Prepare Maven artifact cache
        # https://github.com/actions/cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v1.4.1
        with:
          java-version: 1.8

      - name: Prepare Maven settings
        # https://github.com/s4u/maven-settings-action
        uses: s4u/maven-settings-action@v2.1.0
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        with:
          servers: '[{"id": "ossrh", "username": "${{ secrets.OSSRH_USERNAME }}", "password": "${{ secrets.OSSRH_PASSWORD }}"}]'

      - name: Prepare GPG environment
        # https://github.com/crazy-max/ghaction-import-gpg
        uses: crazy-max/ghaction-import-gpg@v2.1.1
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Verify artifacts
        if: github.ref == 'refs/heads/master' != true && startsWith(github.ref, 'refs/tags/') != true
        run: mvn -B verify

      - name: Deploy artifacts
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: mvn -B -Possrh deploy

      - name: Upload coverage report
        # https://github.com/marketplace/actions/codecov
        uses: codecov/codecov-action@v1.0.12
        if: startsWith(github.ref, 'refs/heads/dependabot/') != true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Prepare documentation tag
        id: prepare-documentation-tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=docs_tag_name::${TAG_NAME}-docs"
          
      - name: Publish documentation
        # https://github.com/peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3.6.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          cname: spring-hateoas-siren.ingogriebsch.de
          commit_message: 'docs: publish documentation to gh-pages'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/generated-docs
          tag_message: 'Tag documentation for ${{ steps.prepare-documentation-tag.outputs.tag_name }}'
          tag_name: ${{ steps.prepare-documentation-tag.outputs.docs_tag_name }}
          user_email: 'github-actions[bot]@users.noreply.github.com'
          user_name: 'github-actions[bot]'
